export const FETCH_WORD = 'FETCH_WORD';
export const SET_DIFFICULTY = 'SET_DIFFICULTY';

export const FIND_USER_SUCCESS = 'FIND_USER_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const LOAD_ERROR = 'LOAD_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';